name: CI/CD - Build and Deploy react client

on:
  push:
    branches: ["prod"]

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t araldhafeeri/blazecicd-client:${{ github.sha }} \
            --push \
            .

  update_argocd_repo:
    runs-on: ubuntu-latest
    needs: build_and_push_docker

    steps:
      - name: Checkout ArgoCD repository
        uses: actions/checkout@v4
        with:
          repository: ARAldhafeeri/blazecicd-client-argocd
          path: main
          token: ${{ secrets.ARGOCD_REPO_ACCESS_TOKEN }}

      - name: Update container image
        run: |
          # navigate 
          cd main

          # setup identity 
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Ensure the repository is up to date
          git pull
          # Update the image tag in the deployment.yaml file
          sed -i "s|image: araldhafeeri/blazecicd-client:.*$|image: araldhafeeri/blazecicd-client:${{ github.sha }}|" deployment.yaml
          # Commit and push the changes
          git add deployment.yaml
          git commit -m "Updated image tag to ${{ github.sha }}"
          git push
